; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
monitor_port = COM7
monitor_speed = 9600
upload_protocol = stlink
lib_deps = 
	arduino-libraries/ArduinoModbus
	arduino-libraries/ArduinoRS485
	fanfanlatulipe26/FS_MX1508@^1.1.0
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
	robtillaart/AS5600@^0.6.7
	k-off/A4988@^1.0.0
	gyverlibs/GyverStepper@^2.7.2
	milesburton/DallasTemperature@^4.0.6
	gyverlibs/EncButton@^3.7.4
